config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'challenges/explore'

  root 'challenges#explore'

  get 'barracks/created'
  get 'barracks/participations'
  get 'barracks/important'
  get 'barracks/archived'

  resources :challenges, except: [:edit, :update, :index] do
    member do
      get 'confirm'
      post 'confirmed'
    end
    post 'confirm_result/:party_id', to: 'confirmations#create', as: 'confirm_result'
  end

  devise_for :players

  resources :orbs, only: [:index]

  resources :participations, only: [:create, :index]

  resources :billings, only: [:index, :create, :destroy] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :parties, only: [] do
    resources :participations, only: [:new]
  end

  resources :cases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :player
  belongs_to :party
  has_one :challenge, through: :party
  validates :player_id, :blocks, :party_id, presence: true
  validates :blocks, numericality: {greater_than_or_equal_to: 1}
  # validates :player_id, uniqueness: { scope: :party_id }
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  authorize_resource
  include ParticipationsHelper

  def new
    @party = Party.find(params[:party_id])
    @participation = Participation.new
    @available_orbs = current_player.wallet.orbs
  end

  def create
    @participation = Participation.new(party_id: params[:party_id], player_id: current_player.id, blocks: params[:participation][:blocks].to_i)
    player = Player.find(current_player.id)
    @challenge = Challenge.find(@participation.challenge.id)
    orbs = params[:participation][:blocks].to_i * @challenge.block_size
    @party = Party.find(params[:party_id])
    participation_save(player, orbs, @participation, @challenge)
  end

end

app/helpers/participations_helper.rb
module ParticipationsHelper

  def participation_save(player, orbs, participation, challenge)
    if player.wallet.orbs >= orbs
      ActiveRecord::Base.transaction do
        begin
          participation.save!
          player.wallet.update!(orbs: (player.wallet.orbs - orbs))
          challenge.wallet.update!(orbs: (challenge.wallet.orbs + orbs))
          player.wallet.orbs > 0
        rescue ActiveRecord::Rollback
          redirect_to challenge_path(challenge), alert: "There was a problem joining the challenge."
        end
      end
    else
      redirect_to challenge_path(challenge), alert: "Not enough orbs!"
    end
  end
end

app/views/participations/_modal_new_participation.html.erb
<div class="text-center">
  <h4>Join "<%= @party.description %> "</h4>
</div>
<%= form_with(model: @participation, url: participations_path(party_id: @party.id), remote: true) do |f| %>
  <div class="form-row">
    <div class="col text-center" >
      <%= f.number_field :blocks, class: "form-control", id: "blocks_input", min: 1, required: true %>
      <%= f.label :blocks %>
      (<%= @party.challenge.block_size %> CryptOrbs each)
    </div>
  </div>
  <% remaining = @party.challenge.remaining_blocks%>
  <% if remaining %>
    <div class="form-row">
        <p class="form-control">
          (<%= remaining %> still open)
        </p>
    </div>
  <% end %>
  <div class="text-center">
    <%= f.submit "Let's do this!", class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  var available = <%= @available_orbs %>
  var block_size =  <%= @party.challenge.block_size %>
  $("#blocks_input").keyup(function () {
      $("#available_orbs").html(available - $(this).val() * block_size);
    })
</script>

app/views/participations/create.js.erb
$('#Modal').modal('hide');
$('#party_<%= @participation.party.id %>').append("<li class=\"list-group-item bg-dark\"><%= @participation.player.username %>: <%= @participation.blocks %> blocks (<%= @participation.blocks * @challenge.block_size %> CryptOrbs)</li>");
$('#player_info').html("Welcome <%= j link_to current_player.username, edit_player_registration_path %>, you've got <%= j link_to current_player.wallet.orbs, orbs_path %> orbs.");
$('#player_info').html("Welcome <%= j link_to current_player.username, edit_player_registration_path %>, you've got <%= j link_to current_player.wallet.orbs, orbs_path %> orbs.");
$('#notices').html("<p class=\"alert alert-success\" role=\"alert\" id=\"notice\">You have joined <%= @party.description %></p>")

app/views/participations/new.js.erb
$('#modal_form').html("<%= j render 'participations/modal_new_participation' %>")
$('#modal_footer').html("<p>(<span id=\"available_orbs\"><%= @available_orbs %></span> CryptOrbs available for challenges)</p>")
$('#Modal').modal('show')