config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'challenges/explore'

  root 'challenges#explore'

  get 'barracks/created'
  get 'barracks/participations'
  get 'barracks/important'
  get 'barracks/archived'

  resources :challenges, except: [:edit, :update, :index] do
    member do
      get 'confirm'
      post 'confirmed'
    end
    post 'confirm_result/:party_id', to: 'confirmations#create', as: 'confirm_result'
  end

  devise_for :players

  resources :orbs, only: [:index]

  resources :participations, only: [:create, :index]

  resources :billings, only: [:index, :create, :destroy] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :parties, only: [] do
    resources :participations, only: [:new]
  end

  resources :cases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">
    <img src="https://throne.help/users/throne/imgExtCatalog/big/26_m765.png" width="30" height="30" class="d-inline-block align-top" alt="Project Cuprite">
    Cuprite
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if player_signed_in? %>
        <span class="navbar-text" id="player_info">
          <%= current_player.username.capitalize %>, you've got <span style="color: lightblue"><%= current_player.wallet.orbs %></span> orbs.
        </span>
      <% end %>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if player_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= challenges_explore_path %>">Explore</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= barracks_participations_path %>">Barracks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= orbs_path %>">Equip</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= destroy_player_session_path %>" data-method="delete">Log out</a>
        </li>

      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_player_session_path %>">Sign in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_player_registration_path %>">Sign up</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>