config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'challenges/explore'

  root 'challenges#explore'

  get 'barracks/created'
  get 'barracks/participations'
  get 'barracks/important'
  get 'barracks/archived'

  resources :challenges, except: [:edit, :update, :index] do
    member do
      get 'confirm'
      post 'confirmed'
    end
    post 'confirm_result/:party_id', to: 'confirmations#create', as: 'confirm_result'
  end

  devise_for :players

  resources :orbs, only: [:index]

  resources :participations, only: [:create, :index]

  resources :billings, only: [:index, :create, :destroy] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :parties, only: [] do
    resources :participations, only: [:new]
  end

  resources :cases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/barracks_controller.rb
class BarracksController < ApplicationController

  def created
    @challenges = current_player.created
  end

  def participations
    @challenges = current_player.current_participations
  end

  def important
    @challenges = current_player.requiring_attention
  end

  def archived
    @challenges = current_player.archived_challenges
  end

end

app/helpers/barracks_helper.rb
module BarracksHelper
end

app/views/barracks/archived.html.erb
<br>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_participations_path %>">Participations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_created_path %>">My challenges</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_important_path %>">Needs attention</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Archived</a>
  </li>
</ul>

<% if @challenges.present? %>
  <div class="row">
    <%= render '/challenges/list'%>
  </div>
<% end %>

app/views/barracks/created.html.erb
<br>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_participations_path %> ">Participations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">My challenges</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_important_path %>">Needs attention</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_archived_path %>">Archived</a>
  </li>
</ul>

<% if @challenges.present? %>
  <div class="row">
    <%= render '/challenges/list'%>
  </div>
<% end %>

app/views/barracks/important.html.erb
<br>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_participations_path %> ">Participations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_created_path %>">My challenges</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Needs attention</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_archived_path %>">Archived</a>
  </li>
</ul>

<% if @challenges.present? %>
  <div class="row">
    <%= render '/challenges/list'%>
  </div>
<% end %>

app/views/barracks/participations.html.erb
<br>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">Participations</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_created_path %>">My challenges</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_important_path %>">Needs attention</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= barracks_archived_path %>">Archived</a>
  </li>
</ul>

<% if @challenges.present? %>
  <div class="row">
    <%= render '/challenges/list'%>
  </div>
<% end %>