config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'challenges/explore'

  root 'challenges#explore'

  get 'barracks/created'
  get 'barracks/participations'
  get 'barracks/important'
  get 'barracks/archived'

  resources :challenges, except: [:edit, :update, :index] do
    member do
      get 'confirm'
      post 'confirmed'
    end
    post 'confirm_result/:party_id', to: 'confirmations#create', as: 'confirm_result'
  end

  devise_for :players

  resources :orbs, only: [:index]

  resources :participations, only: [:create, :index]

  resources :billings, only: [:index, :create, :destroy] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  resources :parties, only: [] do
    resources :participations, only: [:new]
  end

  resources :cases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord

  validates :title, :description, :closing_date, :expiration_date, :block_size, :creator_id, presence: true
  validates :min_honor, :capped, :block_size, numericality: {greater_than_or_equal_to: 0}
  belongs_to :language
  belongs_to :creator, class_name: 'Player', foreign_key: 'creator_id'
  has_one :wallet, as: :owner, dependent: :destroy
  has_many :challenge_tags, dependent: :destroy
  has_many :tags, through: :challenge_tags
  has_many :verifiers, dependent: :destroy
  has_many :parties, dependent: :destroy
  has_many :participations, through: :parties
  has_many :confirmations, through: :parties
  accepts_nested_attributes_for :verifiers
  accepts_nested_attributes_for :parties
  has_one_attached :picture
  enum status:{
    pending: 0,
    open: 1,
    closed: 2,
    confirming_results: 3,
    on_case: 4,
    archived: 5
  }
  validate :datetime, on: :create
  after_create :wallet_assignation

  def self.status_checker
    challenges = Challenge.where.not(status: 'archived')
    challenges.each do |challenge|
      if challenge.pending? && ((Time.current - challenge.created_at) / 1.hour) > 72
        challenge.destroy
      elsif challenge.open? && challenge.closing_date < Time.current
        challenge.closed!
      elsif (challenge.closed? || challenge.open?) && challenge.expiration_date < Time.current
        challenge.confirming_results!
      elsif challenge.confirming_results? && ((Time.current - c.created_at) / 1.hour) > 48
        if challenge.agreement?
          challenge.distribute_and_archive
        else
          challenge.open_case
        end
      end
    end
  end

  def agreement?
    party = self.confirmations.first.party_id
    self.confirmations.each do |confirmation|
      return false if party != confirmation.party_id
      party = confirmation.party_id
    end
    self.confirmations.first.party.update(winner: true)
    true
  end

  def distribute_and_archive
    winners = {}
    winner_blocks = 0
    total_blocks = 0
    self.participations.each do |participation|
      total_blocks += participation.blocks
      if participation.party.winner == true
        if winners.key?(participation.player_id)
          winners[participation.player_id] += participation.blocks
        else
          winners[participation.player_id] = participation.blocks
        end
        winner_blocks += participation.blocks
      end
    end
    excedent = 0
    winners.each do |player_id, blocks|
      proportion = winner_blocks / blocks.to_f
      if total_blocks * proportion % 1 > 0
        part = (total_blocks * proportion).floor
        excedent += total_blocks * proportion % 1
        self.send_orbs((part * self.block_size).to_i, Player.find(player_id).wallet)
        self.send_orbs((excedent * self.block_size).floor.to_i, Player.find_by(email: 'claudio@claudio.com').wallet)
      else
        part = total_blocks * proportion
        self.send_orbs((part * self.block_size).to_i, Player.find(player_id).wallet)
      end
    end
    self.archived!
  end

  def send_orbs(orbs, destination)
    Transaction.create(orbs: orbs, origin_wallet: self.wallet, destination_wallet: destination)
    self.wallet.update(orbs: (self.wallet.orbs - orbs))
    destination.update(orbs: (destination.orbs + orbs))
  end

  def open_case
    #por hacer
  end

  def winner_party
    self.parties.each do |party|
      return party if party.winner == true
    end
    nil
  end

  def winner?(player)
    winner_party = self.winner_party
    player.participations.select { |p| p if p.challenge.archived? }
    participations.each do |p|
      return true if p.party == winner_party
    end
    false
  end

  def confirmed?(player)
    player.confirmations.each do |confirmation|
      return true if confirmation.challenge == self
    end
    false
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def blocks_in_play
    blocks = 0
    self.participations.each do |participation|
      blocks += participation.blocks
    end
    blocks
  end

  def remaining_blocks
    if self.capped == 0
      return false
    else
      self.capped - blocks_in_play
    end
  end

  private

  def wallet_assignation
    Wallet.create(owner: self, active: true, orbs: 0)
  end

  def datetime
    now = DateTime.now
    if expiration_date < now
      errors.add(:expiration_date, "can't be in the past")
    elsif closing_date < now
      errors.add(:closing_date, "can't be in the past")
    elsif expiration_date < closing_date
      errors.add(:expiration_date, "can't occur before the closing date")
    end
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_player!, only: [:show, :new]
  before_action :set_challenge, only: [:show, :confirm, :confirmed, :destroy]
  load_and_authorize_resource except: [:explore, :show]
  include ChallengesHelper

  def explore
    if params[:tags].present?
      @challenges = find_by_tag(params[:tags])
    else
      @challenges = Challenge.all.where(status: "open")
    end
  end

  def show
    @parties = @challenge.parties
    @player_id = current_player.id
  end

  def confirm
    @participation = Participation.new
  end

  def confirmed
    if @challenge.open!
      session.delete(:new_challenge)
      redirect_to challenge_path(@challenge.id), notice: "Challenge created and open to other players!"
    end
  end

  def new
    @challenge = Challenge.new
    @challenge.verifiers.build
    @challenge.parties.build
  end

  def create
    @challenge = parse_challenge_data(challenge_params, params)
    if @challenge.save
      redirect_to challenge_path(@challenge.id)
    else
      message = ''
      @challenge.errors.full_messages.each do |error|
        message += (error.to_s + ' ')
      end
      redirect_back(fallback_location: new_challenge_path, alert: message)
    end
  end

  def destroy
    if @challenge.pending?
      @challenge.destroy
      redirect_to root_path, alert: 'Challenge canceled'
    end
  end

  private

  def challenge_params
    params.require(:challenge).permit(
      :all_tags, :title, :description, :local, :min_honor, :picture,
      :language_id, :capped, :block_size,
      verifiers_attributes: [:description],
      parties_attributes: [:description, :weight]
    )
  end

  # def authenticate_creator
  #   redirect_to new_player_session unless
  #   Challenge.find(params[:id]).creator == current_player
  # end

  def set_challenge
    @challenge = Challenge.find(params[:id])
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper

  def find_by_tag(search)
    challenges = []
    tags = []
    search.split(',').each do |searched_tag|
      Tag.where('name LIKE ?', "%#{searched_tag.strip}%").each do |tag|
        tags << tag
      end
    end
    tags.each do |tag|
      tag.challenges.each do |challenge|
        challenges << challenge
      end
    end
    challenges
  end

  def parse_challenge_data(parameters, params)
    if params[:challenge][:local].to_i == 1
      parameters[:local] = true
    else
      parameters[:local] = false
    end
    parameters[:expiration_date] = "#{params[:challenge]['expiration_date(1i)']}-#{params[:challenge]['expiration_date(2i)']}-#{params[:challenge]['expiration_date(3i)']} #{params[:challenge]['expiration_date(4i)']}:#{params[:challenge]['expiration_date(5i)']}:00 -0300"
    parameters[:closing_date] = "#{params[:challenge]['closing_date(1i)']}-#{params[:challenge]['closing_date(2i)']}-#{params[:challenge]['closing_date(3i)']} #{params[:challenge]['closing_date(4i)']}:#{params[:challenge]['closing_date(5i)']}:00 -0300"
    parameters[:creator_id] = current_player.id
    Challenge.new(parameters)
  end

end

app/views/challenges/_confirming_result.html.erb
<br>
<% if @challenge.confirmed?(current_player) %>
  <h1>Waiting for other player confirmations of the result</h1>
<% else %>
  <h1>Confirm the results</h1>
<% end %>

<div class="card text-white bg-dark mb-3 card border-info">

  <%= image_tag @challenge.picture, class: 'card-img-top' %>

  <div class="card-body">
    <h1 class="card-title"><%= @challenge.title %></h1>
    <p class="card-text"><%= @challenge.description %></p>
  </div>

  <ol class="list-group list-group-flush">
    <ol class="list-group-item bg-secondary text-center">Verifiers
      <% @challenge.verifiers.each do |verifier| %>
        <li class="list-group-item bg-dark"><%= verifier.description %></li>
      <% end %>
    </ol>
  </ol>
</div>

<% if @challenge.confirmed?(current_player) %>
  <div class="text-center">
    <h2><%= distance_of_time_in_words(@challenge.closing_date, DateTime.now) %> left</h2>
  </div>
<% else %>
  <div class="text-center">
    <h2>Choose the winner party according to the verifiers</h2><h5>(conflictive cases will be reviewed, lies will result in penalization.)</h5>
    <i class="fa fa-angle-double-down fa-3x"></i>
  </div>

  <% @challenge.parties.each do |party| %>
    <a href="<%=challenge_confirm_result_path(@challenge.id, party.id) %>" data-method="post">
      <div class="card text-white bg-info mb-3" style="text-align: center; margin-top: 10px; margin-bottom: 10px">
        <div class="card-body">
          <h5 class="card-title"><%= party.description %></h5>
        </div>
      </div>
    </a>
  <% end %>
<% end %>

app/views/challenges/_list.html.erb
<% @challenges.each do |challenge| %>
  <div class="col-md-3">
    <div class="card bg-light mb-3" style="text-align: center; margin-top: 10px; margin-bottom: 10px">
      <div class="card-header">
        <% if challenge.pending? %>
          Pending your confirmation
        <% elsif challenge.archived? %>
          <% if challenge.winner?(current_player) %>
            Challenge won!
          <% else %>
           lost
          <% end %>
        <% elsif challenge.closed? %>
          closed / <%= distance_of_time_in_words(challenge.expiration_date, DateTime.now) %> left
        <% elsif challenge.confirming_results? %>
          <% if challenge.confirmed?(current_player) %>
            Waiting other players confirmations
          <% else %>
            <strong> CONFIRMATION NEEDED </strong>
          <% end %>
          (<%= distance_of_time_in_words(challenge.closing_date, DateTime.now) %> left)
        <% else %>
          <% if challenge.participations.present? %>
            <%= challenge.participations.count %> playing /
          <% end %>
          <%= distance_of_time_in_words(challenge.closing_date, DateTime.now) %> left
        <% end %>
      </div>
      <a href="<%= challenge_path(challenge.id) %>"><h5 class="card-title"><%= image_tag challenge.picture, class: 'card-img-top' %></h5></a>
      <div class="card-body">
        <a href="<%= challenge_path(challenge.id) %>"><h5 class="card-title"><%= challenge.title %></h5></a>
        <p class="card-text"><%= challenge.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <% challenge.parties.each do |party| %>
        <li class="list-group-item"><%= party.description %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/challenges/_modal_new_participation.html.erb
<div class="text-center">
  <h4>Join "<%= @party.description %> "</h4>
</div>
<%= form_with model: @participation, url: participations_path(party_id: @party.id), local: false do |f| %>
  <div class="form-row">
    <div class="col text-center" >
      <%= f.number_field :blocks, class: "form-control", id: "blocks_input", min: 1, required: true %>
      <%= f.label :blocks %>
      (<%= @party.challenge.block_size %> CryptOrbs each)
    </div>
  </div>
  <% remaining = @party.challenge.remaining_blocks%>
  <% if remaining %>
    <div class="form-row">
        <p class="form-control">
          (<%= remaining %> still open)
        </p>
    </div>
  <% end %>
  <div class="text-center">
    <%= f.submit "Let's do this!", class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  var available = <%= @available_orbs %>
  var block_size =  <%= @party.challenge.block_size %>
  $("#blocks_input").keyup(function () {
      $("#available_orbs").html(available - $(this).val() * block_size);
    })
</script>

app/views/challenges/_open.html.erb
<br>
<div class="card text-white bg-dark mb-3 card border-info">
  <div class="row">
    <div class="col-md-6">
      <h5 class="card-header">
        <%= @challenge.status.capitalize %>
        <% if @challenge.open? %>
         until: <%= @challenge.closing_date.to_formatted_s(:short) %> (<%= distance_of_time_in_words(@challenge.closing_date, DateTime.now) %> left)
        <% end %>
    </div>
    <div class="col-md-6">
      <h6 class="card-header text-right">
      <% if @challenge.capped > 0 %>
        | Capped to <%= @challenge.capped %>.
      <% end %>
      <% if @challenge.parties.first.weight > 0 %>
        | Forced proportion.
      <% end %>
      <% if @challenge.min_honor > 0 %>
        | <%= @challenge.min_honor %> min Honor required. |
      <% end %>
    </h6>
      </div>
  </div>

  <%= image_tag @challenge.picture, class: 'card-img-top' %>

  <div class="card-img-overlay" style="margin: 20px;">
    <br>
    <% @challenge.tags.each do |tag| %>
      <p class="card-text"><%= tag.name %></p>
    <% end %>
  </div>

  <div class="card-footer text-center">Block size of <%= @challenge.block_size %> CryptOrbs.</div>

  <div class="card-body">
    <h1 class="card-title"><%= @challenge.title %></h1>
    <p class="card-text"><%= @challenge.description %></p>
    <p class="card-text"><small class="text-muted">By <%= @challenge.creator.username %></small></p>
  </div>

  <ol class="list-group list-group-flush">
    <ol class="list-group-item bg-secondary text-center">Parties
    <% @challenge.parties.each do |party| %>
      <ol class="list-group bg-dark" id="party_<%= party.id %>">
        <%= link_to party.description, new_party_participation_path(party_id: party.id), remote: true, class: "btn btn-info" %>
      <% party.participations.each do |participation| %>
          <li class="list-group-item bg-dark"><%= participation.player.username %>: <%= participation.blocks %> blocks (<%= participation.blocks * @challenge.block_size %> CryptOrbs)</li>
      <% end %>
      </ol>
    <% end %>
    </ol>
  </ol>
  <ol class="list-group list-group-flush">
    <ol class="list-group-item bg-secondary text-center">Verifiers
      <% @challenge.verifiers.each do |verifier| %>
        <li class="list-group-item bg-dark"><%= verifier.description %></li>
      <% end %>
    </ol>
  </ol>
</div>

<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Accept the challenge</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal_form">
      </div>
      <div class="modal-footer text-center" id="modal_footer">
      </div>
    </div>
  </div>
</div>

app/views/challenges/_pending.html.erb
<br>
<h1>Confirm details</h1>

<div class="card text-white bg-dark mb-3 card border-info">
  <div class="row">
    <div class="col-md-6">
      <h5 class="card-header">
        <%= @challenge.status.capitalize %>
        <% if @challenge.open? %>
         until: <%= @challenge.closing_date.to_formatted_s(:short) %> (<%= distance_of_time_in_words(@challenge.closing_date, DateTime.now) %> left)
        <% end %>
    </div>
    <div class="col-md-6">
      <h6 class="card-header text-right">
      <% if @challenge.capped > 0 %>
        | Capped to <%= @challenge.capped %>.
      <% end %>
      <% if @challenge.parties.first.weight > 0 %>
        | Forced proportion.
      <% end %>
      <% if @challenge.min_honor > 0 %>
        | <%= @challenge.min_honor %> min Honor required. |
      <% end %>
    </h6>
      </div>
  </div>

  <%= image_tag @challenge.picture, class: 'card-img-top' %>

  <div class="card-img-overlay" style="margin: 20px;">
    <br>
    <% @challenge.tags.each do |tag| %>
      <p class="card-text"><%= tag.name %></p>
    <% end %>
  </div>

  <div class="card-footer text-center">Block size of <%= @challenge.block_size %> CryptOrbs.</div>

  <div class="card-body">
    <h1 class="card-title"><%= @challenge.title %></h1>
    <p class="card-text"><%= @challenge.description %></p>
    <p class="card-text"><small class="text-muted">By <%= @challenge.creator.username %></small></p>
  </div>

  <ol class="list-group list-group-flush">
    <li class="list-group-item bg-secondary text-center">Parties</li>
    <% @challenge.parties.each do |verifier| %>
      <li class="list-group-item bg-dark"><%= verifier.description %></li>
    <% end %>
  </ol>
  <ol class="list-group list-group-flush">
    <li class="list-group-item bg-secondary text-center">Verifiers</li>
    <% @challenge.verifiers.each do |verifier| %>
      <li class="list-group-item bg-dark"><%= verifier.description %></li>
    <% end %>
  </ol>
</div>

<div class="row">
  <div class="col-md-6">
    <%= link_to 'Cancel creation', challenge_path(@challenge.id), method: :delete, class: "btn btn-danger" %>
  </div>
  <div class="col-md-6 text-right" id="confirm">
    <%= link_to 'Confirm and open', confirmed_challenge_path(@challenge.id), method: :post, class: "btn btn-success" %>
  </div>
</div>

<br>

app/views/challenges/confirm.html.erb
<br>
<div class="card text-white bg-dark mb-3 card border-info">
  <div class="row">
    <div class="col-md-6">
      <h5 class="card-header">
        <%= @challenge.status.capitalize %>
        <% if @challenge.open? %>
         until: <%= @challenge.closing_date.to_formatted_s(:short) %> (<%= distance_of_time_in_words(@challenge.closing_date, DateTime.now) %> left)
        <% end %>
    </div>
    <div class="col-md-6">
      <h6 class="card-header text-right">
      <% if @challenge.capped > 0 %>
        | Capped to <%= @challenge.capped %>.
      <% end %>
      <% if @challenge.parties.first.weight > 0 %>
        | Forced proportion.
      <% end %>
      <% if @challenge.min_honor > 0 %>
        | <%= @challenge.min_honor %> min Honor required. |
      <% end %>
    </h6>
      </div>
  </div>

  <img class="card-img-top" src="<%= @challenge.picture %>" alt="Challenge picture">

  <div class="card-img-overlay">
    <br>
    <% @challenge.tags.each do |tag| %>
      <h5 class="card-text"><%= tag.name %></h5>
    <% end %>
  </div>

  <div class="card-footer text-center">Block size of <%= @challenge.block_size %> CryptOrbs.</div>

  <div class="card-body">
    <h1 class="card-title"><%= @challenge.title %></h1>
    <p class="card-text"><%= @challenge.description %></p>
    <p class="card-text"><small class="text-muted">By <%= @challenge.creator.username %></small></p>
  </div>

  <ol class="list-group list-group-flush">
    <li class="list-group-item bg-secondary text-center">Parties</li>
    <% @challenge.parties.each do |verifier| %>
      <li class="list-group-item bg-dark"><%= verifier.description %></li>
    <% end %>
  </ol>
  <ol class="list-group list-group-flush">
    <li class="list-group-item bg-secondary text-center">Verifiers</li>
    <% @challenge.verifiers.each do |verifier| %>
      <li class="list-group-item bg-dark"><%= verifier.description %></li>
    <% end %>
  </ol>
</div>

<div class="row">
  <div class="col-md-6">
    <%= link_to 'Back to edit', challenge_path(@challenge.id), method: :delete, class: "btn btn-danger" %>
  </div>
  <div class="col-md-6 text-right" id="confirm">
    <%= link_to 'Confirm this challenge', confirmed_challenge_path(@challenge.id), method: :post, class: "btn btn-success" %>
  </div>
</div>

app/views/challenges/new.html.erb
<br>
<div class="text-center">
  <h1>Time to challenge other players</h1>
</div>

<%= form_with(model: [@challenge], url: challenges_path, local: true, multipart:true) do |f| %>
  <div class="jumbotron" id="general_data">
  <div class="form-row">
    <div class="col-md-8">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", required: true %>
    </div>
    <div class="col-md-4">
      <%= f.label :picture %><br />
      <%= f.file_field :picture, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", required: true %>
  </div>

  <div class="form-group">
  <%= f.label :tags %>
  <%= f.text_field :all_tags, class: "form-control", required: true %>
  <small id="tagsHelpBlock" class="form-text text-muted"> Separated by commas.</small>
  </div>
</div>

<div class="text-center" id="continue_1">
  <i class="fa fa-angle-double-down fa-3x" onclick=load_next(1)></i>
</div>

<div class="jumbotron" id="specification_data">
  <div class="form-row" id="parties">
  <%= f.fields_for :parties do |parties| %>
    <div class="col-md-9">
      <%= parties.label :party_1 %>
      <%= parties.text_field :description, class: "form-control", required: true %>
      <small id="partyHelpBlock" class="form-text text-muted"> Side or possible result. At least 2 parties must be added.</small>
    </div>
    <div class="col-md-3">
      <%= parties.label :forced_weight %>
      <%= parties.number_field :weight, class: "form-control", value: 0 , required: true %>
      <small id="forcedHelpBlock" class="form-text text-muted"> Force a specific challengers ratio, default (0) is organic grow. Must be all 0 or sum 100.</small>
    </div>
  <% end %>
  </div>

  <div class="text-center">
    <button id="add_party" class="btn btn-warning"><%= fa_icon "plus fa-4x" %></button>
  </div>

  <div class="form-group" id="verifiers">
  <%= f.fields_for :verifiers do |verifiers| %>
    <%= verifiers.label :verifier_1 %>
    <%= verifiers.text_field :description, class: "form-control", required: true %>
    <small id="verifiersHelpBlock" class="form-text text-muted"> Objective or near-objective criteria to establish the final result.</small>
  <% end %>
</div>
<div class="text-center">
  <button id="add_verifier" class="btn btn-warning"><%= fa_icon "plus fa-4x" %></button>
</div>
</div>

<div class="text-center" id="continue_2">
  <i class="fa fa-angle-double-down fa-3x" onclick=load_next(2)></i>
</div>

<div class="jumbotron" id="numeric_data">
  <div class="form-row">
    <div class="offset-md-3 col-md-2">
      <%= f.label :local? %><br />
      <%= f.check_box :local, class: "form-control" %>
      <small id="localHelpBlock" class="form-text text-muted"> Challenge targeted to local players </small>
    </div>
    <div class="col-md-2">
      <%= f.label :language %><br />
      <%= f.collection_select :language_id, Language.order(:name), :id, :name, include_blank: false %>
    </div>
    <div class="col-md-2">
      <%= f.label :min_honor %>
      <%= f.number_field :min_honor, class: "form-control", value: 0 %>
      <small id="honorHelpBlock" class="form-text text-muted"> Establish a minimum honor to join.</small>
    </div>
  </div>
  <div class="form-row">
    <div class="offset-md-3 col-md-3">
      <%= f.label :block_size %>
      <%= f.number_field :block_size, class: "form-control", required: true %>
      <small id="blocksizeHelpBlock" class="form-text text-muted"> Establish how many CryptOrbs has each block.</small>
    </div>
    <div class="col-md-3">
      <%= f.label :max_blocks %>
      <%= f.number_field :capped, class: "form-control", value: 0, required: true %>
      <small id="cappedHelpBlock" class="form-text text-muted"> Establish a maximum number of joinable blocks.</small>
    </div>
  </div>
</div>

<div class="text-center" id="continue_3">
  <i class="fa fa-angle-double-down fa-3x" onclick=load_next(3)></i>
</div>

<div class="jumbotron text-center" id="deadlines_data">
  <div class="form-group">
    <div class="col">
      <%= f.label :closing_date %>
      <%= f.datetime_select(:closing_date) %>
    <small id="closingdateHelpBlock" class="form-text text-muted"> Establish the joining deadline. </small>
    </div>
    <br>
    <div class="col">
      <%= f.label :expiration_date %>
      <%= f.datetime_select(:expiration_date) %>
      <small id="expirationdateHelpBlock" class="form-text text-muted"> Establish the challenge final date.</small>
    </div>
  </div>
</div>

  <div class="text-center" id="continue_4">
    <%= f.submit "Continue", class: "btn btn-primary" %>
  </div>
  <br>

<% end %>

  <script>
    <% if session[:new_challenge].blank? %>
      specification = $("#specification_data")
      numeric = $("#numeric_data")
      deadlines = $("#deadlines_data")
      specification.hide()
      numeric.hide()
      deadlines.hide()
      $("#continue_2").hide()
      $("#continue_3").hide()
      $("#continue_4").hide()

      function load_next(data) {
        if (data == 1) {
          specification.show()
        } else if (data == 2) {
          numeric.show()
        } else if (data == 3) {
          deadlines.show()
        }
        $("#continue_" + data).hide()
        $("#continue_" + (data + 1)).show()
      }
    <% else %>
      $("#continue_1").hide()
      $("#continue_2").hide()
      $("#continue_3").hide()
    <% end %>
    party_count = 2
    verifier_count = 2
    add("party")
    $("#add_party").click(function(event) {
      event.preventDefault();
      add("party")
    })
    $("#add_verifier").click(function(event) {
      event.preventDefault();
      add("verifier")
    })

    function add(option) {
      if (option == "party") {
        new_party = "<div class=\"col-md-9\"><label for=\"challenge_parties_attributes_" + (party_count - 1) + "_party_1\">Party " + party_count + "</label><input class=\"form-control\" value=\"\" name=\"challenge[parties_attributes][" + (party_count - 1) + "][description]\" id=\"challenge_parties_attributes_" + (party_count - 1) + "_description\" type=\"text\" required=\"required\"></div> <div class=\"col-md-3\"> <label for=\"challenge_parties_attributes_" + (party_count - 1) + "_forced_weight\">Forced weight</label> <input class=\"form-control\" value=\"0\" name=\"challenge[parties_attributes][" + (party_count - 1) + "][weight]\" id=\"challenge_parties_attributes_" + (party_count - 1) + "_weight\" type=\"number\" required=\"required\">";
        $("#parties").append(new_party);
        party_count++
      } else {
        new_challenge = "<label for=\"challenge_verifiers_attributes_" + (verifier_count - 1) + "_verifier_1\">Verifier " + (verifier_count) + "</label><input class=\"form-control\" value=\"\" name=\"challenge[verifiers_attributes][" + (verifier_count - 1) + "][description]\" id=\"challenge_verifiers_attributes_" + (verifier_count - 1) + "_description\" type=\"text\" required=\"required\">"
        $("#verifiers").append(new_challenge);
      }

    }
  </script>